title: DECK

description_de: >
  Akademische Sammelkartenspiel-Gemeinschaft an der Universität Innsbruck.

description_en: >
  Academic Trading Card Game community at the University of Innsbruck.

description: >
  Akademische Sammelkartenspiel-Gemeinschaft an der Universität Innsbruck.

show_downloads: false
google_analytics:
theme: jekyll-theme-midnight

url: https://deck-innsbruck.at
baseurl: ""