title: DECK
description: >
  Akademische Sammelkartenspiel-Gemeinschaft an der Universität Innsbruck.
  Wir spielen Magic: The Gathering, Lorcana, Riftbound, Seeker Chronicles
  und weitere Trading Card Games.

show_downloads: false
google_analytics:
theme: jekyll-theme-midnight

url: https://deck-innsbruck.at
baseurl: ""